apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana-agent.fullname" . }}-headless
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: 'None'
  selector:
    {{- include "grafana-agent.selectorLabels" . | nindent 4 }}
  ports:
    - name: http-metrics
      port: {{ .Values.agent.listenPort }}
      targetPort: {{ .Values.agent.listenPort }}
      protocol: "TCP"
    - name: faro
      port: {{ .Values.agent.faroPort }}
      targetPort: {{ .Values.agent.faroPort }}
      protocol: "TCP"
{{- range $portMap := .Values.agent.extraPorts }}
    - name: {{ $portMap.name }}
      port: {{ $portMap.port }}
      targetPort: {{ $portMap.targetPort }}
      protocol: {{ coalesce $portMap.protocol "TCP" }}
{{- end }}
