# Test rendering of the chart with the controller explicitly set to StatefulSet and autoscaling enabled.
controller:
  type: statefulset
  autoscaling:
    enabled: true
  enableStatefulSetAutoDeletePVC: true
agent:
  resources:
    requests:
      memory: 100Mi
