blank_issues_enabled: true
contact_links:
  - name: Grafana Agent community support
    url: https://github.com/grafana/agent/discussions
    about: If you need help or support, ask questions in Github Discussions.
  - name: Grafana Agent Slack
    url: https://slack.grafana.com/
    about: "Join the #agent slack channel to chat about Grafana Agent in real-time."
  - name: Grafana Cloud or Grafana Enterprise
    url: https://grafana.com/profile/org#support
    about: Open a support ticket for help with Grafana Cloud or Grafana Enterprise.
