{{- if eq .Values.controller.type "daemonset" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "grafana-agent.fullname" . }}
  namespace: {{ include "grafana-agent.namespace" . }}
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      {{- include "grafana-agent.selectorLabels" . | nindent 6 }}
  template:
    {{- include "grafana-agent.pod-template" . | nindent 4 }}
  {{- with .Values.controller.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
