version: "3"
services:

  mimir:
    image: grafana/mimir:latest
    volumes:
      - ./configs/mimir:/etc/mimir-config
    entrypoint:
      - /bin/mimir
      - -config.file=/etc/mimir-config/mimir.yaml
    ports:
      - "9009:9009"

  loki:
    image: grafana/loki:2.8.3
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.85.0
    restart: always
    command: ["--config=/etc/otel-collector-contrib.yaml", ""]
    volumes:
      - ./configs/otel-collector-contrib/otel-collector-contrib.yaml:/etc/otel-collector-contrib.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP exporter
    environment:
      - OTEL_EXPORTER_ENDPOINT=${OTEL_EXPORTER_ENDPOINT:-http://host.docker.internal:8080}
  
  demo-client:
    build:
      dockerfile: ./integration-tests/configs/otel-gen-client/Dockerfile
      context: ..
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - DEMO_SERVER_ENDPOINT=http://demo-server:7080/hello
    depends_on:
      - demo-server

  demo-server:
    build:
      dockerfile: ./integration-tests/configs/otel-gen-server/Dockerfile
      context: ..
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    ports:
      - "7080"
    depends_on:
      - otel-collector
  
  prom-gen:
    build:
      dockerfile: ./integration-tests/configs/prom-gen/Dockerfile
      context: ..
    ports:
      - "9001:9001"