name: Check Linux build image

on:
  pull_request:
    paths:
      - 'build-image/*'

jobs:
  check-linux-build-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create test Linux build image
        uses: docker/build-push-action@v5
        with:
          context: ./build-image
          push: false
          tags: grafana/agent-build-image:latest