name: Check Containers

on:
  workflow_call:

jobs:
  check-linux-containers:
    name: Check Linux container (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: grafana/agent
            make: make agent-image
            path: cmd/grafana-agent/Dockerfile
          - name: grafana/agentctl
            make: make agentctl-image
            path: cmd/grafana-agentctl/Dockerfile
          - name: grafana/agent-operator
            make: make operator-image
            path: cmd/grafana-agent-operator/Dockerfile
    steps:
      - name: Checkout code ğŸ›ï¸
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build container
        run: ${{ matrix.make }}

  check-windows-containers:
    name: Check Windows container (${{ matrix.name }})
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - name: grafana/agent
            argument: agent
            path: cmd/grafana-agent/Dockerfile.windows
          - name: grafana/agentctl
            argument: agentctl
            path: cmd/grafana-agentctl/Dockerfile.windows
    steps:
      - name: Checkout code ğŸ›ï¸
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build container
        run: |
          & "C:/Program Files/git/bin/bash.exe" ./tools/ci/docker-containers-windows ${{ matrix.argument }}
        shell: powershell
