name: Test Helm chart
on: pull_request
jobs:
  regenerate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Regenerate docs
        run: |
          docker run --rm \
            -v "$(pwd)/operations/helm/charts/grafana-agent:/helm-docs" \
            -u "$(id -u)" \
            jnorwood/helm-docs
          if ! git diff --exit-code; then
            echo "Helm chart documentation is not up to date. Please run 'make generate-helm-docs' and commit changes!" >&2
            exit 1
          fi

  regenerate-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.10.3

      - name: Regenerate tests
        run: |
          make generate-helm-tests
          if [ ! -z "$(git status --porcelain)" ]; then
            echo "Helm chart tests are not up to date. Please run 'make generate-helm-tests' and commit changes!" >&2
            exit 1
          fi

  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.10.3

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          check-latest: true

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Determine changed charts
        id: list-changed
        run: |
          changed=$(ct list-changed --config ./operations/helm/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Lint charts
        run: ct lint --config ./operations/helm/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Add dependency chart repos
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

      - name: Install Prometheus Operator CRDs
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm install my-prometheus-operator-crds prometheus-community/prometheus-operator-crds --version 6.0.0

      - name: Test charts
        run: ct install --config ./operations/helm/ct.yaml
