name: Publish Release

on:
  push:
    tags:
      - v*
    branches:
      - main

permissions:
  contents: read

jobs:
  publish-linux-containers:
    name: Publish Linux container (${{ matrix.container }})
    runs-on: ubuntu-latest-8-cores
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        container: [agent, agent-boringcrypto, agentctl, agent-operator]
    steps:
      - name: Login to DockerHub (from vault) ğŸ”‘
        uses: grafana/shared-workflows/actions/dockerhub-login@13fb504e3bfe323c1188bf244970d94b2d336e86 # dockerhub-login-v1.0.1

      - name: Checkout code ğŸ›ï¸
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup QEMU âš™ï¸
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx ğŸ³
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Publish container ğŸš€
        run: ./tools/ci/docker-containers ${{ matrix.container }}
        env:
          DRONE_TAG: ${{ github.ref_name }}

  publish-windows-containers:
    name: Publish Windows container (${{ matrix.container }})
    runs-on: github-hosted-windows-x64-large
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        container: [agent, agentctl]
    steps:
      - name: Login to DockerHub (from vault) ğŸ”‘
        uses: grafana/shared-workflows/actions/dockerhub-login@13fb504e3bfe323c1188bf244970d94b2d336e86 # dockerhub-login-v1.0.1

      - name: Checkout code ğŸ›ï¸
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build containers ğŸ—ï¸
        run: |
          & "C:/Program Files/git/bin/bash.exe" ./tools/ci/docker-containers-windows ${{ matrix.container }}
        shell: powershell
        env:
          DRONE_TAG: ${{ github.ref_name }}

  publish-release:
    name: Publish release
    runs-on: ubuntu-latest-8-cores
    needs: [publish-linux-containers, publish-windows-containers]
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Login to DockerHub (from vault) ğŸ”‘
        uses: grafana/shared-workflows/actions/dockerhub-login@13fb504e3bfe323c1188bf244970d94b2d336e86 # dockerhub-login-v1.0.1

      - name: Checkout code ğŸ›ï¸
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup QEMU âš™ï¸
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx ğŸ³
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Set up Go âš™ï¸
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Build release artifacts ğŸ“¦
        run: make -k -j4 RELEASE_BUILD=1 VERSION=${GITHUB_REF_NAME} dist

      - name: Publish release ğŸš€
        run: |
          VERSION=${GITHUB_REF_NAME} RELEASE_DOC_TAG=$(echo ${GITHUB_REF_NAME} | awk -F '.' '{print $1"."$2}') ./tools/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
