name: Stale check
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'
permissions:
  issues: write
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5.2.0
        with:
          close-issue-reason: not_planned
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: >
            This issue has been automatically marked as stale because it has
            not had any activity in the past 30 days.

            The next time this stale check runs, the stale label will be
            removed if there is new activity. The issue will be closed in 7
            days if there is no new activity.

            Thank you for your contributions!
          stale-pr-message: >
            This PR has been automatically marked as stale because it has not
            had any activity in the past 30 days.

            The next time this stale check runs, the stale label will be
            removed if there is new activity. The issue will be closed in 7
            days if there is no new activity.

            Thank you for your contributions!
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-issue-labels: keepalive,proposal,outdated-dependency,dev-branch
          exempt-pr-labels: keepalive,proposal,outdated-dependency,dev-branch
