name: Test CRDs

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test-crds:
    name: Test CRDs
    runs-on: ubuntu-latest
    container:
      # TODO: Keep this in sync with build-container.mk somehow
      image: grafana/agent-build-image:0.44.2
    steps:
      - name: Checkout code ðŸ›Žï¸
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Mark repository as safe ðŸ”’
        run: git status || git config --system --add safe.directory "$GITHUB_WORKSPACE"

      - name: Regenerate CRDs ðŸ“‹
        run: |
          make generate-crds
          ERR_MSG="Custom Resource Definitions are out of date. Please run 'make generate-crds' and commit changes!"
          if [ ! -z "$(git status --porcelain)" ]; then echo $ERR_MSG >&2; exit 1; fi
