name: Update build images

on:
  push:
    tags:
      - 'build-image/v*'

permissions:
  contents: read

env:
  DOCKER_IMAGE: grafana/agent-build-image

jobs:
  linux-build:
    runs-on: ubuntu-latest-8-cores
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        build:
          - runtime: golang:1.24.3-bullseye
          - runtime: mcr.microsoft.com/oss/go/microsoft/golang:1.24.3-bullseye
            suffix: "-boringcrypto"
    steps:
      - name: Checkout code ðŸ›Žï¸
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Extract tag ðŸ·ï¸
        id: extract_tag
        env:
          FULL_TAG: ${{ github.ref_name }}
        run: echo "IMAGE_TAG=${FULL_TAG##*/v}${{ matrix.build.suffix }}" >> $GITHUB_OUTPUT

      - name: Login to DockerHub (from vault) ðŸ”‘
        uses: grafana/shared-workflows/actions/dockerhub-login@13fb504e3bfe323c1188bf244970d94b2d336e86 # dockerhub-login-v1.0.1

      - name: Setup QEMU âš™ï¸
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx ðŸ³
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Build and push Linux images ðŸš€
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
        with:
          context: ./build-image
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ steps.extract_tag.outputs.IMAGE_TAG }}
          build-args: GO_RUNTIME=${{ matrix.build.runtime }}

  windows-build:
    runs-on: github-hosted-windows-x64-large
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code ðŸ›Žï¸
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Extract tag ðŸ·ï¸
        id: extract_tag
        shell: bash
        env:
          FULL_TAG: ${{ github.ref_name }}
        run: echo "IMAGE_TAG=${FULL_TAG##*/v}-windows" >> $GITHUB_OUTPUT

      - name: Login to DockerHub (from vault) ðŸ”‘
        uses: grafana/shared-workflows/actions/dockerhub-login@13fb504e3bfe323c1188bf244970d94b2d336e86 # dockerhub-login-v1.0.1

      - name: Build and push Windows image ðŸš€
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:$env:IMAGE_TAG ./build-image/windows
          docker push ${{ env.DOCKER_IMAGE }}:$env:IMAGE_TAG
        env:
          IMAGE_TAG: ${{ steps.extract_tag.outputs.IMAGE_TAG }}
